language: python
python:
  - "3.6"

# install dependencies
install:
  - pip install -r requirements.txt

# run tests and collect coverage information
script:
  - pytest --cov=./

# send coverage information to codecov
after_success:
  - codecov -t $CODECOV_TOKEN
